export enum ControlCommandEnum {
  command = 'command',
  takeoff = 'takeoff',
  land = 'land',
  streamon = 'streamon',
  streamoff = 'streamoff',
  emergency = 'emergency',
  up = 'up',
  down = 'down',
  left = 'left',
  right = 'right',
  forward = 'forward',
  back = 'back',
  cw = 'cw',
  ccw = 'ccw',
  flip = 'flip',
  go = 'go',
  stop = 'stop',
  curve = 'curve',
  jump = 'jump',
}
